# Generated by Django 3.2.6 on 2021-08-20 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imobiliaria',
            unique_together={('nome', 'endereco')},
        ),
    ]
