# Generated by Django 3.2.6 on 2021-08-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_alter_imobiliaria_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedades', to='imoveis.imobiliaria'),
        ),
    ]
