# Generated by Django 3.2.6 on 2021-08-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_auto_20210821_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='finalidade',
            field=models.CharField(choices=[('Residencial', 'Residencial'), ('Escritorio', 'Escritorio')], max_length=255, null=True),
        ),
    ]
