# Generated by Django 3.2.6 on 2021-08-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_alter_imovel_finalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='imobiliaria',
            unique_together=set(),
        ),
    ]
