# Generated by Django 3.2.6 on 2021-08-24 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_auto_20210823_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Imóvel',
                'verbose_name_plural': 'Tipos de Imóveis',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_imovel', to='imoveis.tipo'),
        ),
    ]
